### ISSUE TITLE
module compatibility

### ISSUE THREAD

**Issue by TrejGun** [liaoliaots/nestjs-redis#49]
Heya! 
We are using your awesome module in production on two projects, thank you so much
Please shed a light on module compatibility with newly released nestjs8 and write a migration guide if any

**Comment by liaoliaots** [comment]
I'm waiting for the @nestjs/terminus package to be updated to v8, because npm v7 will cause conflict for now, and for stability.
^-^ ^-^

**Comment by liaoliaots** [comment]
https://github.com/nestjs/terminus/issues/1316

**Comment by liaoliaots** [comment]
https://github.com/nestjs/terminus/issues/1316

**Comment by liaoliaots** [comment]
[nestjs-redis v3.0.0-next.0 has been released](https://www.npmjs.com/package/@liaoliaots/nestjs-redis/v/3.0.0-next.0).

**Comment by TrejGun** [comment]
🥳
