### ISSUE TITLE
Can't resolve decorator InjectRedis

### ISSUE THREAD

**Issue by newmizanur** [liaoliaots/nestjs-redis#61]
## Current behaviour

Error: Nest can't resolve dependencies 
NestJS version: 7.6

## Input Code

```ts
import { Redis } from 'ioredis';
import { InjectRedis } from '@liaoliaots/nestjs-redis';

constructor(@InjectRedis('cache') private readonly clientCache: Redis) 
```

**Comment by liaoliaots** [comment]
The code of document uses `importHelpers` option in tsconfig.json.

You can try this:
**import * as Redis from 'ioredis';**

**@InjectRedis('cache') private readonly clientCache: Redis.Redis**

**Comment by liaoliaots** [comment]
Could you provide a minimal repository, please?
✿◡‿◡

**Comment by newmizanur** [comment]
My bad, I import it at the wrong place(Core Module). Working fine. ty!
