### ISSUE TITLE
@nestjs/terminus should not be a required dependency

### ISSUE THREAD

**Issue by sboli** [liaoliaots/nestjs-redis#86]
## Current behavior
@nestjs/terminus a good practice to monitor app availability. And is a must have the second you deploy to K8s. But you should not enforce this on users of this library.

As is @nestjs/terminus must be installed in order for this library to work. This should be easily decoupled.

**Comment by liaoliaots** [comment]
I will publish v3.0.0 today or tomorrow, @nestjs/terminus will be a optional dep.
